USE [master]
GO

/****** Object:  Database [PhoneCompany]    Script Date: 04.04.2024 7:40:06 ******/
CREATE DATABASE [PhoneCompany]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PhoneCompany', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PhoneCompany.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PhoneCompany_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PhoneCompany_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PhoneCompany].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PhoneCompany] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PhoneCompany] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PhoneCompany] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PhoneCompany] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PhoneCompany] SET ARITHABORT OFF 
GO

ALTER DATABASE [PhoneCompany] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PhoneCompany] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PhoneCompany] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PhoneCompany] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PhoneCompany] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PhoneCompany] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PhoneCompany] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PhoneCompany] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PhoneCompany] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PhoneCompany] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PhoneCompany] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PhoneCompany] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PhoneCompany] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PhoneCompany] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PhoneCompany] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PhoneCompany] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PhoneCompany] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PhoneCompany] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PhoneCompany] SET  MULTI_USER 
GO

ALTER DATABASE [PhoneCompany] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PhoneCompany] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PhoneCompany] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PhoneCompany] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PhoneCompany] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PhoneCompany] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PhoneCompany] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PhoneCompany] SET  READ_WRITE 
GO

